// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkIywi1ol9wwZd89bNzl0m3iBVLzBkZDQ',
    appId: '1:742173059472:web:d6b7515593f55f9ff6ab15',
    messagingSenderId: '742173059472',
    projectId: 'navigate-ff149',
    authDomain: 'navigate-ff149.firebaseapp.com',
    storageBucket: 'navigate-ff149.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCe3Pa4Q-lB1LKRwK84S9vPN487D4tp8uk',
    appId: '1:742173059472:android:985c4e3044715f21f6ab15',
    messagingSenderId: '742173059472',
    projectId: 'navigate-ff149',
    storageBucket: 'navigate-ff149.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAABPCeercfIffDiMTmlHix448OW0_eapI',
    appId: '1:742173059472:ios:3d08d68c0cd2061af6ab15',
    messagingSenderId: '742173059472',
    projectId: 'navigate-ff149',
    storageBucket: 'navigate-ff149.firebasestorage.app',
    iosBundleId: 'com.lgt.your.locator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAABPCeercfIffDiMTmlHix448OW0_eapI',
    appId: '1:742173059472:ios:ad643b15399615aaf6ab15',
    messagingSenderId: '742173059472',
    projectId: 'navigate-ff149',
    storageBucket: 'navigate-ff149.firebasestorage.app',
    iosBundleId: 'com.app.crypoexchange',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkIywi1ol9wwZd89bNzl0m3iBVLzBkZDQ',
    appId: '1:742173059472:web:694a7b89991e822bf6ab15',
    messagingSenderId: '742173059472',
    projectId: 'navigate-ff149',
    authDomain: 'navigate-ff149.firebaseapp.com',
    storageBucket: 'navigate-ff149.firebasestorage.app',
  );
}
